#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake $targetType



wmake $targetType fvModels/VoFCavitation
wmake $targetType fvModels/VoFBoiling/compressibleBoiling
wmake $targetType fvModels/VoFBoiling
wmake $targetType fvModels/VoFSolidificationMelting
wmake $targetType fvModels/VoFClouds
wmake $targetType fvModels/VoFTurbulenceDamping
#------------------------------------------------------------------------------
