#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean

wclean libso fvModels/VoFTurbulenceDamping
wclean libso fvModels/VoFClouds
wclean libso fvModels/VoFCavitation
wclean libso fvModels/VoFSolidificationMelting
wclean libso fvModels/VoFBoiling
wclean libso fvModels/VoFBoiling/compressibleBoiling

#------------------------------------------------------------------------------
